name: test script install

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  fedora-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4           
    - name: test zsh autoinstall in fedora
      run: docker build . --file Dockerfile.fedora.zsh-test
  arch-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: test zsh autoinstall in arch
      run : docker build . --file Dockerfile.arch.zsh-test 
